# Gitpod configuration file
tasks:
  - command: |
      export LT_USERNAME="yellaboinaudaykumar"
      export LT_ACCESS_KEY="LT_ZKb9IPvLjLrDlWnfVirI1vWDjaFUrrmH3rFoLVprT7CI8KF"
      npm install
      npx playwright install
      npx playwright install --with-deps
      npx playwright test
      node playwright-parallel.js
