# Gitpod configuration file
tasks:
  - name: Install dependencies
    init: npm install  # Install project dependencies
    command: npm init playwright@latest  # Install Playwright dependencies

  
  - name: Run Playwright Tests
    command: npx playwright test 

